name: My Actions
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
    - main
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16.18.1"
          cache: ${{ steps.detect-package-manager.outputs.manager }}
      - name: test node
        run : node -v
      - uses: actions/checkout@v3
      - name: compilation et suite de test unitaires
        run: npm install
      - name: tests
        run: npm run test
